# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8ZtbAwkpHycRM1-AhkzV0kt7Wq1oJa2
"""

import streamlit as st

# Page config
st.set_page_config(
    page_title="Smart App",
    page_icon="✨",
    layout="centered"
)

# Custom style
st.markdown("""
    <style>
    .main {
        text-align: center;
    }
    .stButton>button {
        background-color: #4CAF50;
        color: white;
        border-radius: 10px;
        height: 3em;
        width: 100%;
        font-size: 16px;
    }
    </style>
""", unsafe_allow_html=True)

st.title("✨ أهلاً بك في التطبيق الذكي")

# Session state (to remember user)
if "submitted" not in st.session_state:
    st.session_state.submitted = False

name = st.text_input("📝 اكتب اسمك")
age = st.slider("🎂 اختر عمرك", 0, 100, 18)
gender = st.radio("⚧ اختر جنسك", ["male", "female"])

photo = st.file_uploader("📸 ارفع صورتك (اختياري)", type=["png", "jpg", "jpeg"])

if st.button("🚀 عرض البيانات"):
    if name.strip() == "":
        st.error("❌ لازم تكتب اسمك!")
    else:
        st.session_state.submitted = True

if st.session_state.submitted:
    st.success(f"🎉 أهلاً يا {name}!")

    col1, col2 = st.columns(2)

    with col1:
        st.write(f"👤 الاسم: {name}")
        st.write(f"🎂 العمر: {age}")
        st.write(f"⚧ الجنس: {gender}")

    with col2:
        if photo:
            st.image(photo, caption="صورتك", use_column_width=True)
        else:
            st.info("📷 ما رفعت صورة")

if age < 13:
        st.warning("👶 انت صغير! استمتع بوقتك 😄")
        st.balloons()
    elif age < 25:
        st.info("🔥 عمر النشاط والطاقة!")
        st.balloons()
    else:
        st.info("💼 شخص ناضج 👌")
        st.snow()

st.progress(age / 100)